### ISSUE TITLE
让osu运行在UAC低完整性下而不是UAC高完整性

### ISSUE THREAD

**Issue by telecomadm1145** [KyuubiRan/BeatmapDownloader#2]
在打开了UAC的电脑上，OTD默认是低完整性运行，然后用这玩意启动的osu是高完整性的...
低完整性应用在高完整性应用聚焦的时候是无法发送输入的
简单来说，OTD寄了
除非OTD也管理员

UAC降权的办法特别简单:万能的explorer，传入一个可执行路径作为参数后会贴心的给你降权打开这个可执行文件
懒得交pr了希望作者看一下（

**Comment by KyuubiRan** [comment]
坏了 我没研究过uac ~~你还是pr一下吧~~

**Comment by telecomadm1145** [comment]
草

**Comment by telecomadm1145** [comment]
我先去叫hxd过来水pr了（
![图片](https://github.com/KyuubiRan/BeatmapDownloader/assets/47657299/f42ac0fb-ba67-4e4d-aa32-c74f95aa54ab)
hxd不来我应该会等上完分就做（

**Comment by KyuubiRan** [comment]
好的
