### ISSUE TITLE
[Bug] Location of injector

### ISSUE THREAD

**Issue by miRceLzeS** [KyuubiRan/BeatmapDownloader#6]
**Description**
Firstly, my osu directory looks like:
---- Osu
    - Osu.exe
    - Tools
       -- injector.exe
Then I followed your video and run injector.exe. It started a cmd window and stuck at "[Info] Downloader is up to date", having no GUI displayed. But when I moved the Tools dir outside of the root dir (named Osu as above), everything went correctly.

By the way, this tool is great and thx for saving my time :D.

**Comment by KyuubiRan** [comment]
sry reply so late, please make sure you're not run osu as `Compatibility Mode` and don't place downlaoder into osu folder
